kind: 'vision'
s3_data_dir: s3://imagenet1k-sdl/train/ #s3://sdl-cifar10/train/ #s3://imagenet1k-sdl/train/, s3://sdl-cifar10/train/
batch_size: 128 #chunk_size  = number of files per chunk
max_lookahead_batches: 10
max_prefetch_workers: 10
keep_alive_ping_iterval: 15
shuffle: False
drop_last: False
num_dataset_partitions: 1