AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda
  Sample SAM Template for lambda
Globals:
  Function:
    Timeout: 30
    MemorySize: 3072
  Api:
    BinaryMediaTypes:
      - image/png
      - image/jpg
      - image/jpeg
Resources:
  CreateVisionBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateVisionTrainingBatch  # Set your custom function name here
      PackageType: Image
      Architectures:
        - x86_64 #arm64 #x86_64
      # Events:
      #   CreateBatch:
      #     Type: Api
      #     Properties:
      #       Path: /create_vision_batch
      #       Method: post
      Role: arn:aws:iam::590178426343:role/SIONLambdaRole
      VpcConfig:  # Add VPC configuration here
        SecurityGroupIds:
          - sg-0e3cfe7dde2d319b2  # Replace with your security group ID
        SubnetIds:
          - subnet-0719017fb24af22ac  # Replace with your subnet ID
          - subnet-076f5a2c0e07e6b1e  # Replace with your subnet ID
      # EphemeralStorage:
      #   Size: 10240  # Set ephemeral storage to 10 GB
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./create_vision_batch
      DockerTag: python3.9-v1
      
# Outputs:
  # CreateBatchApi:
  #   Description: "API Gateway endpoint URL for Prod stage for CreateBatch function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create_batch/"
  # CreateVisionBatchFunction:
  #   Description: "CreateBatch Lambda Function ARN"
  #   Value: !GetAtt CreateVisionBatchFunction.Arn
  # CreateVisionBatchFunction:
  #   Description: "IAM Role created for CreateBatch function"
  #   Value: !GetAtt CreateVisionBatchFunction.Arn
