defaults:
  - _self_
  - workload: vision #language, vision
  # - override hydra/hydra_logging: disabled  
  # - override hydra/job_logging: disabled

cache_address: 10.0.19.221:6378  #10.0.24.192:6378  #10.0.24.192:6378 # '10.0.24.192:6378' # '10.0.29.229:6378' 10.0.20.157:6378'
simulate_mode: True
prefetch_lambda_name: 'CreateVisionTrainingBatch'
cost_cap_per_hour: 10
partitions_per_dataset: 1
batch_size: 128
lookahead_steps: 50
inital_prefetch_concurrency: 10

hydra:
  run:
    dir: .  # Current directory or a specific directory where Ray Tune expects to find it
  sweep:
    dir: .  # Same as above
  output_subdir: null
  job_logging:
    level: DISABLE  # Disable job-specific logging
  hydra_logging:
    level: DISABLE  # Disable Hydra-specific logging
