# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "supertextfunction"
aws_region = "us-west-2"
confirm_changeset = true
allow_sam_cli_role_creation = true
disable_rollback = true
createtextbatchfunction_authentication = true
save_arguments = false

[default.build.parameters]
cached = false
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"  # Add CAPABILITY_NAMED_IAM here
resolve_s3 = true
s3_prefix = "supertextfunction"
region = "us-west-2"
force_upload = true
# image_repositories = ["CreateVisiontextFunction=590178426343.dkr.ecr.us-west-2.amazonaws.com/supertextfunction31012d32/createtextbatchfunction44a1e0adrepo"]
[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = false

[default.local_start_api.parameters]
warm_containers = "EAGER"
#warm_containers = "LAZY"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
#warm_containers = "LAZY"
